<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/admin/osii.css', 'Osii'));
$this->htmlElement('body')->appendAttribute('class', 'osii import show');
?>

<?php echo $this->pageTitle($this->translate('Manage import'), 1, $this->translate('Omeka S Item Importer'), $import->label()); ?>

<div id="page-actions">
    <?php echo $import->link($this->translate('Edit import'), 'edit', ['class' => 'button']); ?>
</div>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Imports'), $this->url('admin/osii-import', ['action' => 'browse'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->translate('Manage'); ?>
</div>

<?php if ($import->canPrepareImport()): ?>

<p><?php echo $this->translate('Prepare the import below.'); ?></p>

<?php
echo $this->sectionNav([
    'map-data-types' => $this->translate('Map data types'),
    'remote-properties' => $this->translate('Remote properties'),
    'remote-classes' => $this->translate('Remote classes'),
]);
?>

<div id="map-data-types" class="section active">
    <h3><?php echo $this->translate('Map data types'); ?></h3>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Remote data type'); ?></th>
                <th><?php echo $this->translate('Remote value count'); ?></th>
                <th><?php echo $this->translate('Local data type'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php $index = 0; ?>
        <?php foreach ($import->snapshotDataTypes() as $remoteDataTypeId => $remoteDataType): ?>
            <tr>
                <td>
                    <?php echo $remoteDataTypeId; ?>
                    <input type="hidden"
                        name="<?php echo $this->escapeHtml(sprintf('data_type_map[%s][remote]', $index)); ?>"
                        value="<?php echo $this->escapeHtml($remoteDataTypeId); ?>">
                </td>
                <td><?php echo $remoteDataType['count']; ?></td>
                <td>
                    <?php $localDataTypeSelect->setName(sprintf('data_type_map[%s][local]', $index)); ?>
                    <?php echo $this->formElement($localDataTypeSelect); ?>
                </td>
            </tr>
        <?php $index++; ?>
        <?php endforeach; ?>
        <tbody>
    </table>
</div>

<div id="remote-properties" class="section">
    <h3><?php echo $this->translate('Remote properties'); ?></h3>
    <?php foreach ($import->snapshotProperties() as $remoteVocabNamespaceUri => $remoteProperties): ?>
    <ul>
        <li><?php echo sprintf($this->translate('Vocabulary label: %s'), $import->snapshotVocabularies()[$remoteVocabNamespaceUri]['label']); ?></li>
        <li><?php echo sprintf($this->translate('Vocabulary namespace URI: %s'), $remoteVocabNamespaceUri); ?></li>
    </ul>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Remote local name'); ?></th>
                <th><?php echo $this->translate('Remote label'); ?></th>
                <th><?php echo $this->translate('Remote value count'); ?></th>
                <th><?php echo $this->translate('On local install?'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($remoteProperties as $remotePropertyId => $remoteProperty): ?>
            <?php $propertyUri = sprintf('%s%s', $remoteVocabNamespaceUri, $remoteProperty['local_name']); ?>
            <tr>
                <td><?php echo $remoteProperty['local_name']; ?></td>
                <td><?php echo $remoteProperty['label']; ?></td>
                <td><?php echo $remoteProperty['count']; ?></td>
                <td><?php echo in_array($propertyUri, $localProperties) ? sprintf('<span style="color: green">%s</span>', $this->translate('Yes')) : sprintf('<span style="color: red">%s</span>', $this->translate('No')); ?></td>
            </tr>
        <?php endforeach; ?>
        <tbody>
    </table>
    <?php endforeach; ?>
</div>

<div id="remote-classes" class="section">
    <h3><?php echo $this->translate('Remote classes'); ?></h3>
    <?php foreach ($import->snapshotClasses() as $remoteVocabNamespaceUri => $remoteClasses): ?>
    <ul>
        <li><?php echo sprintf($this->translate('Vocabulary label: %s'), $import->snapshotVocabularies()[$remoteVocabNamespaceUri]['label']); ?></li>
        <li><?php echo sprintf($this->translate('Vocabulary namespace URI: %s'), $remoteVocabNamespaceUri); ?></li>
    </ul>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Remote local name'); ?></th>
                <th><?php echo $this->translate('Remote label'); ?></th>
                <th><?php echo $this->translate('Remote item count'); ?></th>
                <th><?php echo $this->translate('On local install?'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($remoteClasses as $remoteClassId => $remoteClass): ?>
            <?php $classUri = sprintf('%s%s', $remoteVocabNamespaceUri, $remoteClass['local_name']); ?>
            <tr>
                <td><?php echo $remoteClass['local_name']; ?></td>
                <td><?php echo $remoteClass['label']; ?></td>
                <td><?php echo $remoteClass['count']; ?></td>
                <td><?php echo in_array($classUri, $localClasses) ? sprintf('<span style="color: green">%s</span>', $this->translate('Yes')) : sprintf('<span style="color: red">%s</span>', $this->translate('No')); ?></td>
            </tr>
        <?php endforeach; ?>
        <tbody>
    </table>
    <?php endforeach; ?>
</div>

<?php else: ?>
<p><?php echo $this->translate('Prepare import is not available.'); ?></p>
<?php endif; ?>

<div id="import-metadata" class="sidebar always-open">
    <h3><?php echo $this->translate('Actions'); ?></h3>
    <div class="meta-group">
        <h4><?php echo $this->translate('Snapshot'); ?></h4>
        <div class="value">
            <?php echo sprintf('Status: %s', $this->translate($import->snapshotStatusLabel())); ?>
            <?php if ($import->canStopSnapshot()): ?>
            <?php echo $this->hyperlink($this->translate('Refresh'), $this->url(null, [], true), ['class' => 'button']); ?>
            <?php endif; ?>
        </div>
        <div class="value">
            <?php echo sprintf($this->translate('Last completed: %s'), $import->snapshotCompleted() ? $this->i18n()->dateFormat($import->snapshotCompleted(), 'medium', 'medium') : $this->translate('[n/a]')); ?>
        </div>
        <div class="value">
            <?php if ($import->canDoSnapshot()): ?>
                <?php echo $this->hyperlink($this->translate('Take snapshot'), '#', [
                'class' => 'sidebar-content',
                'style' => 'color: green;',
                'data-sidebar-selector' => '#do-snapshot',
            ]); ?>
            <?php endif; ?>
            <?php if ($import->canStopSnapshot()): ?>
            <?php echo $this->hyperlink($this->translate('Stop snapshot'), '#', [
                'class' => 'sidebar-content',
                'style' => 'color: red;',
                'data-sidebar-selector' => '#stop-snapshot',
            ]); ?>
            <?php endif; ?>
        </div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Import'); ?></h4>
        <div class="value">
            <?php if ($import->canDoImport()): ?>
                <?php echo $this->hyperlink($this->translate('Import'), '#', [
                'class' => 'sidebar-content',
                'style' => 'color: green;',
                'data-sidebar-selector' => '#do-import',
            ]); ?>
            <?php endif; ?>
        </div>
    </div>
    <h3><?php echo $this->translate('Import metadata'); ?></h3>
    <div class="meta-group">
        <h4><?php echo $this->translate('Label'); ?></h4>
        <div class="value"><?php echo $import->label(); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Root endpoint'); ?></h4>
        <div class="value"><?php echo $import->rootEndpoint(); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Key identity'); ?></h4>
        <div class="value"><?php echo $import->keyIdentity() ?: $this->translate('[n/a]'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Key credential'); ?></h4>
        <div class="value"><?php echo $import->keyCredential() ?: $this->translate('[n/a]'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Remote query'); ?></h4>
        <div class="value"><?php echo $import->remoteQuery() ?: $this->translate('[n/a]'); ?></div>
    </div>
    <div class="meta-group">
        <?php $localItemSet = $import->localItemSet(); ?>
        <h4><?php echo $this->translate('Local item set'); ?></h4>
        <div class="value"><?php echo $localItemSet ? $localItemSet->title() : $this->translate('[n/a]'); ?></div>
    </div>
</div>

<div id="do-snapshot" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Snapshot'); ?></h3>
    <p><?php echo $this->translate('Take a snapshot of the remote items in their current state. This will gather the data needed to reconcile the local installation with the remote one.'); ?></p>
    <?php echo $this->form($formDoSnapshot); ?>
</div>

<div id="stop-snapshot" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Snapshot'); ?></h3>
    <p><?php echo $this->translate('Stop the currently running snapshot.'); ?></p>
    <?php echo $this->form($formStopSnapshot); ?>
</div>

<div id="do-import" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Import'); ?></h3>
    <p><?php echo $this->translate('Import the current snapshot. This will add new items and update existing items.'); ?></p>
    <?php echo $this->form($formDoImport); ?>
</div>
