<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/admin/osii.css', 'Osii'));
$this->htmlElement('body')->appendAttribute('class', 'osii import show');
?>

<?php echo $this->pageTitle($this->translate('Manage import'), 1, $this->translate('Omeka S Item Importer'), $import->label()); ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php echo $import->link($this->translate('Edit import'), 'edit', ['class' => 'button']); ?>
    <?php if ($import->canPrepareImport()): ?>
    <input type="submit" value="<?php echo $this->escapeHtml($this->translate('Submit')); ?>">
    <?php endif; ?>
</div>

<div class="breadcrumbs">
    <?php echo $this->hyperlink($this->translate('Imports'), $this->url('admin/osii-import', ['action' => 'browse'], true)); ?>
    <div class="separator"></div>
    <?php echo $this->translate('Manage'); ?>
</div>

<?php if ($import->canPrepareImport()): ?>

<p><?php echo $this->translate('Prepare the import below.'); ?></p>

<ul>
    <li><?php echo sprintf($this->translate('Items in snapshot: %s'), count($import->snapshotItems())); ?></li>
</ul>

<?php
echo $this->sectionNav([
    'snapshot-data-types' => $this->translate('Snapshot data types'),
    'snapshot-properties' => $this->translate('Snapshot properties'),
    'snapshot-classes' => $this->translate('Snapshot classes'),
]);
?>

<div id="snapshot-data-types" class="section active">
    <h3><?php echo $this->translate('Snapshot data types'); ?></h3>
    <?php if ($remoteDataTypes): ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Remote data type'); ?></th>
                <th><?php echo $this->translate('Remote value count'); ?></th>
                <th><?php echo $this->translate('Local data type'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php $index = 0; ?>
        <?php foreach ($remoteDataTypes as $remoteDataTypeId => $remoteDataType): ?>
            <tr>
                <td>
                    <?php echo $remoteDataTypeId; ?>
                    <input type="hidden"
                        name="<?php echo $this->escapeHtml(sprintf('data_type_map[%s][remote]', $index)); ?>"
                        value="<?php echo $this->escapeHtml($remoteDataTypeId); ?>">
                </td>
                <td><?php echo $remoteDataType['count']; ?></td>
                <td>
                    <?php
                    $localDataTypeSelect->setName(sprintf('data_type_map[%s][local]', $index));
                    $localDataType = $import->dataTypeMap()[$remoteDataTypeId] ?? null;
                    $localDataTypeSelect->setValue($localDataType);
                    ?>
                    <?php echo $this->formElement($localDataTypeSelect); ?>
                </td>
            </tr>
        <?php $index++; ?>
        <?php endforeach; ?>
        <tbody>
    </table>
    <?php else: ?>
    <div class="no-resources">
        <p><?php echo $this->translate('No data types in snapshot.'); ?></p>
    </div>
    <?php endif; ?>
</div>

<div id="snapshot-properties" class="section">
    <h3><?php echo $this->translate('Snapshot properties'); ?></h3>
    <?php if ($remoteProperties): ?>
    <?php foreach ($remoteProperties as $vocabularyId => $properties): ?>
    <?php $vocabulary = $import->snapshotVocabularies()[$vocabularyId]; ?>
    <ul>
        <li><?php echo sprintf($this->translate('Vocabulary label: %s'), $vocabulary['label']); ?></li>
        <li><?php echo sprintf($this->translate('Vocabulary namespace URI: %s'), $vocabulary['namespace_uri']); ?></li>
    </ul>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Remote local name'); ?></th>
                <th><?php echo $this->translate('Remote label'); ?></th>
                <th><?php echo $this->translate('Remote value count'); ?></th>
                <th><?php echo $this->translate('On local install?'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($properties as $propertyId => $property): ?>
            <?php $propertyUri = sprintf('%s%s', $vocabulary['namespace_uri'], $property['local_name']); ?>
            <tr>
                <td><?php echo $property['local_name']; ?></td>
                <td><?php echo $property['label']; ?></td>
                <td><?php echo $property['count']; ?></td>
                <td><?php echo in_array($propertyUri, $localProperties) ? sprintf('<span style="color: green">%s</span>', $this->translate('Yes')) : sprintf('<span style="color: red">%s</span>', $this->translate('No')); ?></td>
            </tr>
        <?php endforeach; ?>
        <tbody>
    </table>
    <?php endforeach; ?>
    <?php else: ?>
    <div class="no-resources">
        <p><?php echo $this->translate('No properties in snapshot.'); ?></p>
    </div>
    <?php endif; ?>
</div>

<div id="snapshot-classes" class="section">
    <h3><?php echo $this->translate('Snapshot classes'); ?></h3>
    <?php if ($remoteClasses): ?>
    <?php foreach ($remoteClasses as $vocabularyId => $classes): ?>
    <?php $vocabulary = $import->snapshotVocabularies()[$vocabularyId]; ?>
    <ul>
        <li><?php echo sprintf($this->translate('Vocabulary label: %s'), $vocabulary['label']); ?></li>
        <li><?php echo sprintf($this->translate('Vocabulary namespace URI: %s'), $vocabulary['namespace_uri']); ?></li>
    </ul>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $this->translate('Remote local name'); ?></th>
                <th><?php echo $this->translate('Remote label'); ?></th>
                <th><?php echo $this->translate('Remote item count'); ?></th>
                <th><?php echo $this->translate('On local install?'); ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($classes as $classId => $class): ?>
            <?php $classUri = sprintf('%s%s', $vocabulary['namespace_uri'], $class['local_name']); ?>
            <tr>
                <td><?php echo $class['local_name']; ?></td>
                <td><?php echo $class['label']; ?></td>
                <td><?php echo $class['count']; ?></td>
                <td><?php echo in_array($classUri, $localClasses) ? sprintf('<span style="color: green">%s</span>', $this->translate('Yes')) : sprintf('<span style="color: red">%s</span>', $this->translate('No')); ?></td>
            </tr>
        <?php endforeach; ?>
        <tbody>
    </table>
    <?php endforeach; ?>
    <?php else: ?>
    <div class="no-resources">
        <p><?php echo $this->translate('No classes in snapshot.'); ?></p>
    </div>
    <?php endif; ?>
</div>

<?php else: ?>
<p><?php echo $this->translate('Prepare import is not available now.'); ?></p>
<?php endif; ?>

<?php echo $this->formHidden($form->get('csrf')); ?>
<?php echo $this->form()->closeTag(); ?>

<div id="import-metadata" class="sidebar always-open">
    <h3><?php echo $this->translate('Import actions'); ?></h3>
    <div class="meta-group">
        <h4><?php echo $this->translate('Snapshot'); ?></h4>
        <div class="value">
            <?php echo sprintf($this->translate('Status: %s'), $this->translate($import->snapshotStatusLabel())); ?>
        </div>
        <div class="value">
            <?php echo sprintf($this->translate('Last completed: %s'), $import->snapshotCompleted() ? $this->i18n()->dateFormat($import->snapshotCompleted(), 'medium', 'short') : $this->translate('[n/a]')); ?>
        </div>
        <div class="value">
            <?php
            $actionsMarkup = [];
            if ($import->canDoSnapshot()) {
                $actionsMarkup[] = $this->hyperlink($this->translate('Take snapshot'), '#', [
                    'class' => 'sidebar-content',
                    'data-sidebar-selector' => '#do-snapshot',
                ]);
            }
            if ($import->canStopSnapshot()) {
                $actionsMarkup[] = $this->hyperlink($this->translate('Stop snapshot'), '#', [
                    'class' => 'sidebar-content',
                    'data-sidebar-selector' => '#stop-snapshot',
                ]);
            }
            if ($import->canRefreshSnapshotStatus()) {
                $actionsMarkup[] = $this->hyperlink($this->translate('Refresh status'), $this->url(null, [], true));
            }
            if ($import->canViewSnapshotJob()) {
                $actionsMarkup[] = $this->hyperlink($this->translate('View job'), $this->url('admin/id', ['controller' => 'job', 'id' => $import->snapshotJob()->id()]));
            }
            ?>
            <?php echo implode(' | ', $actionsMarkup); ?>
        </div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Import'); ?></h4>
        <div class="value">
            <?php echo sprintf($this->translate('Status: %s'), $this->translate($import->importStatusLabel())); ?>
        </div>
        <div class="value">
            <?php echo sprintf($this->translate('Last completed: %s'), $import->importCompleted() ? $this->i18n()->dateFormat($import->importCompleted(), 'medium', 'short') : $this->translate('[n/a]')); ?>
        </div>
        <div class="value">
            <?php
            $actionsMarkup = [];
            if ($import->canDoImport()) {
                $actionsMarkup[] = $this->hyperlink($this->translate('Import snapshot'), '#', [
                    'class' => 'sidebar-content',
                    'data-sidebar-selector' => '#do-import',
                ]);
            }
            if ($import->canStopImport()) {
                $actionsMarkup[] = $this->hyperlink($this->translate('Stop import'), '#', [
                    'class' => 'sidebar-content',
                    'data-sidebar-selector' => '#stop-import',
                ]);
            }
            if ($import->canRefreshImportStatus()) {
                $actionsMarkup[] = $this->hyperlink($this->translate('Refresh status'), $this->url(null, [], true));
            }
            if ($import->canViewImportJob()) {
                $actionsMarkup[] = $this->hyperlink($this->translate('View job'), $this->url('admin/id', ['controller' => 'job', 'id' => $import->importJob()->id()]));
            }
            if ($import->canViewItems()) {
                $actionsMarkup[] = $this->hyperlink($this->translate('View items'), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['osii_import_id' => $import->id()]]));
            }
            ?>
            <?php echo implode(' | ', $actionsMarkup); ?>
        </div>
    </div>
    <h3><?php echo $this->translate('Import metadata'); ?></h3>
    <div class="meta-group">
        <h4><?php echo $this->translate('Root endpoint'); ?></h4>
        <div class="value"><?php echo $import->rootEndpoint(); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Query'); ?></h4>
        <div class="value"><?php echo $import->remoteQuery() ?: $this->translate('[n/a]'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Key identity'); ?></h4>
        <div class="value"><?php echo $import->keyIdentity() ?: $this->translate('[n/a]'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Key credential'); ?></h4>
        <div class="value"><?php echo $import->keyCredential() ?: $this->translate('[n/a]'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Import label'); ?></h4>
        <div class="value"><?php echo $import->label(); ?></div>
    </div>
    <div class="meta-group">
        <?php $localItemSet = $import->localItemSet(); ?>
        <h4><?php echo $this->translate('Item set'); ?></h4>
        <div class="value"><?php echo $localItemSet ? $localItemSet->title() : $this->translate('[n/a]'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Delete removed items'); ?></h4>
        <div class="value"><?php echo $import->deleteRemovedItems() ? $this->translate('Yes') : $this->translate('No'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Add remote site URL'); ?></h4>
        <div class="value"><?php echo $import->sourceSite() ?: $this->translate('[n/a]'); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Add remote item URL'); ?></h4>
        <div class="value"><?php echo $import->addSourceItem() ? $this->translate('Yes') : $this->translate('No'); ?></div>
    </div>
</div>

<div id="do-snapshot" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Snapshot'); ?></h3>
    <p><?php echo $this->translate('Take a snapshot of the remote items in their current state. This will gather the data needed to import the items and reconcile the local installation with the remote one.'); ?></p>
    <?php echo $this->form($formDoSnapshot); ?>
</div>

<div id="stop-snapshot" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Snapshot'); ?></h3>
    <p><?php echo $this->translate('Stop the currently running snapshot.'); ?></p>
    <?php echo $this->form($formStopSnapshot); ?>
</div>

<div id="do-import" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Import'); ?></h3>
    <p><?php echo $this->translate('Import the current snapshot. This will add new items and update existing items.'); ?></p>
    <?php echo $this->form($formDoImport); ?>
</div>

<div id="stop-import" class="sidebar">
    <?php echo $this->hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $this->translate('Close')]); ?>
    <h3><?php echo $this->translate('Import'); ?></h3>
    <p><?php echo $this->translate('Stop the currently running import.'); ?></p>
    <?php echo $this->form($formStopImport); ?>
</div>
